In [1]:
import cv2
import numpy as np

In [2]:
# Read Image
im = cv2.imread("C:\\Users\\Mateusz\\Desktop\\AGH\\Pracownia\\Moje proby\\ironman.jpg")
size = im.shape
size
    


(251, 251, 3)

In [3]:
#2D image points. If you change the image, you need to change vector
k = 0

image_points = np.array([
                            (102, 62),      # head
                            (120, 91),      # chest
                            (200-k, 86),      # Left hand
                            (73+k, 160),      # Right hand
                            (192-k/2, 179-0),      # Left foot
                            (162+k/2, 197-0)       # Right foot
                        ], dtype="double")
 
# 3D model points.

model_points = np.array([
                            (14 ,73 , 0),         # head
                            (14 ,41 , 10-0),        # chest
                            (88 ,5  , 0.0),     # Left hand
                            (-63 ,5  , 0.0),      # Right hand    
                            (33,-75, 5),    # Left foot
                            (-4,-75, 5)      # Right foot
 
                        ])


In [4]:
# Camera internals
 
focal_length = size[1]
center = (size[1]/2, size[0]/2)
camera_matrix = np.array(
                         [[focal_length, 0, center[0]],
                         [0, focal_length, center[1]],
                         [0, 0, 1]], dtype = "double"
                         )
 
print ("Camera Matrix :\n {0}".format(camera_matrix))
 
dist_coeffs = np.zeros((4,1)) # Assuming no lens distortion
(success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=1)

print ("Rotation Vector:\n {0}".format(rotation_vector))
print ("Translation Vector:\n {0}".format(translation_vector))
 
# Project a 3D point (0, 0, 1000.0) onto the image plane.
# We use this to draw a line sticking out of the nose
translation_vector1= translation_vector
rotation_vector[0] = 0
rotation_vector[1] = 0
rotation_vector[2] = 0

translation_vector1[0] = 0
translation_vector1[1] = 0
translation_vector1[2] = 0


(nose_end_point2D, jacobian) = cv2.projectPoints(np.array([(0.0, 0.0,100.0)]), rotation_vector, translation_vector1, camera_matrix, dist_coeffs)
print(nose_end_point2D)
for p in image_points:
    cv2.circle(im, (int(p[0]), int(p[1])), 3, (0,0,255), -1)

p1 = ( int(image_points[0][0]), int(image_points[0][1]))
p2 = ( int(nose_end_point2D[0][0][0])+int(image_points[0][0]), int(nose_end_point2D[0][0][1])+int(image_points[0][1]))
 
cv2.line(im, p1, p2, (255,0,0), 2)
 
# Display image
cv2.imshow("Output", im)
cv2.waitKey(0)

Camera Matrix :
 [[251.    0.  125.5]
 [  0.  251.  125.5]
 [  0.    0.    1. ]]
Rotation Vector:
 [[ 2.95713692]
 [-0.79708482]
 [-0.02927242]]
Translation Vector:
 [[  1.644032  ]
 [  5.8418483 ]
 [259.80520372]]
[[[125.5 125.5]]]


-1